---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
    - base 

- hosts: jenkins_master
  become: true
  roles:
    - jenkins_master
